# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/miniai-playground',
                'doc_host': 'https://fredguth.github.io',
                'git_url': 'https://github.com/fredguth/miniai-playground',
                'lib_path': 'miniai_playground'},
  'syms': {'miniai_playground.core': {'miniai_playground.core.foo': ('core.html#foo', 'miniai_playground/core.py')}}}
